// ─── Comparison Specs Data ────────────────────────────────────────────────────
// Hardcoded specs for each product in the catalog, organized by category groups.
// Products without a specific spec value will show "—" in the comparison table.
//
// Production mapping (YITH WooCommerce Compare):
//   Create these as WooCommerce attributes (Products → Attributes), assign values
//   on each product, then enable them under YITH → Compare → Fields to show.
//   Category headers below are visual grouping; in WP, order the attribute fields
//   in YITH settings to match PERFORMANCE → DESIGN → DIMENSIONS.

import { type ComparisonSpecCategory, type ComparisonProductData } from "./types";
import { CATALOG } from "../products";
import imgProductCard from "@/imports/Products/c94192fe59684f294c0e23b040e9535e1b810b60.png";

/** Spec categories and their rows for the comparison table.
 *  `wcSlug` = WooCommerce attribute taxonomy slug (pa_<slug>). */
export const COMPARISON_CATEGORIES: ComparisonSpecCategory[] = [
  {
    category: "PERFORMANCE",
    rows: [
      { label: "Engine selection", key: "engine", wcSlug: "pa_engine" },
      { label: "Power (W / DIN HP)", key: "power", wcSlug: "pa_power" },
      { label: "Shreddable timber diameter", key: "timberDiameter", wcSlug: "pa_timber-diameter" },
      { label: "Capacity", key: "capacity", wcSlug: "pa_capacity" },
      { label: "Chopping speed", key: "choppingSpeed", wcSlug: "pa_chopping-speed" },
      { label: "Shredding technology", key: "shreddingTech", wcSlug: "pa_shredding-technology" },
      { label: "Blades", key: "blades", wcSlug: "pa_blades" },
      { label: "Noise reduction", key: "noiseReduction", wcSlug: "pa_noise-reduction" },
    ],
  },
  {
    category: "DESIGN",
    rows: [
      { label: "Feed intake opening", key: "feedOpening", wcSlug: "pa_feed-opening" },
      { label: "Feed height", key: "feedHeight", wcSlug: "pa_feed-height" },
      { label: "Collecting box capacity", key: "collectionCapacity", wcSlug: "pa_collection-capacity" },
      { label: "Durability", key: "durability", wcSlug: "pa_durability" },
      { label: "Chassis", key: "chassis", wcSlug: "pa_chassis" },
      { label: "Safety", key: "safety", wcSlug: "pa_safety" },
      { label: "Storage dimensions", key: "storageDimensions", wcSlug: "pa_storage-dimensions" },
      { label: "Wheels", key: "wheels", wcSlug: "pa_wheels" },
    ],
  },
  {
    category: "DIMENSIONS",
    rows: [
      { label: "Rotor", key: "rotor", wcSlug: "pa_rotor" },
      { label: "Cutting width", key: "cuttingWidth", wcSlug: "pa_cutting-width" },
      { label: "Transmission", key: "transmission", wcSlug: "pa_transmission" },
      { label: "Dimensions", key: "dimensions", wcSlug: "pa_dimensions" },
      { label: "Noise level", key: "noiseLevel", wcSlug: "pa_noise-level" },
      { label: "Weight", key: "weight", wcSlug: "pa_weight" },
    ],
  },
];

/** Per-product comparison data. Keyed by product id. */
export const COMPARISON_PRODUCT_DATA: Record<number, ComparisonProductData> = {
  1: {
    id: 1,
    name: "Maestro City",
    sku: "MA 001 052 123",
    engine: "5.5 HP B&S XR 750",
    image: imgProductCard,
    specs: {
      engine: "5.5 HP B&S XR 750",
      power: "4.1 kW / 5.5 HP",
      timberDiameter: "Ø 40 mm",
      capacity: "60 litres",
      choppingSpeed: "2,800 rpm",
      shreddingTech: "Chopping Principle™",
      blades: "1 hardened steel blade",
      noiseReduction: "Double-wall chamber, sound-damping material",
      feedOpening: "70 × 45 mm",
      feedHeight: "Low (15 cm lower than Maestro Country)",
      collectionCapacity: "60 litres",
      durability: "Steel shredding chamber, tubular frame",
      chassis: "Tubular steel frame",
      safety: "Automatic anti-blockage system",
      storageDimensions: "1,100 × 600 × 900 mm",
      wheels: "2 transport wheels",
      rotor: "Single-piece hardened rotor",
      cuttingWidth: "N/A",
      transmission: "Direct drive",
      dimensions: "1,100 × 600 × 900 mm",
      noiseLevel: "< 90 dB(A)",
      weight: "62 kg",
    },
  },
  2: {
    id: 2,
    name: "Maestro Country",
    sku: "MA 001 053 124",
    engine: "6.5 HP B&S XR 950",
    image: imgProductCard,
    specs: {
      engine: "6.5 HP B&S XR 950",
      power: "4.8 kW / 6.5 HP",
      timberDiameter: "Ø 45 mm",
      capacity: "60 litres",
      choppingSpeed: "2,800 rpm",
      shreddingTech: "Chopping Principle™",
      blades: "1 hardened steel blade",
      noiseReduction: "Double-wall chamber, sound-damping material",
      feedOpening: "70 × 45 mm",
      feedHeight: "Standard",
      collectionCapacity: "60 litres",
      durability: "Steel shredding chamber, tubular frame",
      chassis: "Tubular steel frame",
      safety: "Automatic anti-blockage system",
      storageDimensions: "1,100 × 600 × 900 mm",
      wheels: "2 transport wheels",
      rotor: "Single-piece hardened rotor",
      cuttingWidth: "N/A",
      transmission: "Direct drive",
      dimensions: "1,100 × 600 × 900 mm",
      noiseLevel: "< 90 dB(A)",
      weight: "65 kg",
    },
  },
  3: {
    id: 3,
    name: "Maestro Country E-Power",
    sku: "MA 001 053 801",
    engine: "4.5 HP 56V DC battery (3200W)",
    image: imgProductCard,
    specs: {
      engine: "56V DC battery (3200W)",
      power: "3.2 kW / 4.5 HP",
      timberDiameter: "Ø 45 mm",
      capacity: "60 litres",
      choppingSpeed: "2,800 rpm",
      shreddingTech: "Chopping Principle™",
      blades: "1 hardened steel blade",
      noiseReduction: "Double-wall chamber, electric motor (quieter)",
      feedOpening: "70 × 45 mm",
      feedHeight: "Standard",
      collectionCapacity: "60 litres",
      durability: "Steel shredding chamber, tubular frame",
      chassis: "Tubular steel frame",
      safety: "Automatic anti-blockage system",
      storageDimensions: "1,100 × 600 × 900 mm",
      wheels: "2 transport wheels",
      rotor: "Single-piece hardened rotor",
      cuttingWidth: "N/A",
      transmission: "Direct drive (electric)",
      dimensions: "1,100 × 600 × 900 mm",
      noiseLevel: "< 85 dB(A)",
      weight: "68 kg",
    },
  },
  4: {
    id: 4,
    name: "Minor 4S",
    sku: "MA 002 013 132",
    engine: "6.5 HP Vanguard",
    image: imgProductCard,
    specs: {
      engine: "6.5 HP Vanguard",
      power: "4.8 kW / 6.5 HP",
      timberDiameter: "Ø 50 mm",
      capacity: "80 litres",
      choppingSpeed: "2,600 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber",
      feedOpening: "80 × 50 mm",
      feedHeight: "Standard",
      collectionCapacity: "80 litres",
      durability: "Heavy-duty steel construction",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage",
      storageDimensions: "1,200 × 650 × 1,000 mm",
      wheels: "2 large transport wheels",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,200 × 650 × 1,000 mm",
      noiseLevel: "< 92 dB(A)",
      weight: "85 kg",
    },
  },
  5: {
    id: 5,
    name: "Minor 4S 6.5 HP Honda GX200",
    sku: "MA 002 013 206",
    engine: "6.5 HP Honda GX200",
    image: imgProductCard,
    specs: {
      engine: "6.5 HP Honda GX200",
      power: "4.8 kW / 6.5 HP",
      timberDiameter: "Ø 50 mm",
      capacity: "80 litres",
      choppingSpeed: "2,600 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber",
      feedOpening: "80 × 50 mm",
      feedHeight: "Standard",
      collectionCapacity: "80 litres",
      durability: "Heavy-duty steel construction",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage",
      storageDimensions: "1,200 × 650 × 1,000 mm",
      wheels: "2 large transport wheels",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,200 × 650 × 1,000 mm",
      noiseLevel: "< 92 dB(A)",
      weight: "85 kg",
    },
  },
  6: {
    id: 6,
    name: "Major 4S PTO",
    sku: "MA 003 013 000",
    engine: "PTO",
    image: imgProductCard,
    specs: {
      engine: "PTO (tractor-mounted)",
      power: "15–30 kW / 20–40 HP (via PTO)",
      timberDiameter: "Ø 80 mm",
      capacity: "N/A (ground discharge)",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber",
      feedOpening: "100 × 60 mm",
      feedHeight: "Elevated",
      collectionCapacity: "N/A (ground discharge)",
      durability: "Heavy-duty steel, tractor-grade",
      chassis: "3-point linkage mounted",
      safety: "PTO safety guard, emergency stop",
      storageDimensions: "1,400 × 700 × 1,100 mm",
      wheels: "N/A (tractor mounted)",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "PTO shaft drive",
      dimensions: "1,400 × 700 × 1,100 mm",
      noiseLevel: "< 95 dB(A)",
      weight: "120 kg",
    },
  },
  7: {
    id: 7,
    name: "Major 4S 9 HP Honda GX270",
    sku: "MA 003 013 208",
    engine: "9.0 HP Honda GX270",
    image: imgProductCard,
    specs: {
      engine: "9.0 HP Honda GX270",
      power: "6.7 kW / 9.0 HP",
      timberDiameter: "Ø 60 mm",
      capacity: "100 litres",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber",
      feedOpening: "90 × 55 mm",
      feedHeight: "Standard",
      collectionCapacity: "100 litres",
      durability: "Heavy-duty steel construction",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage",
      storageDimensions: "1,300 × 680 × 1,050 mm",
      wheels: "2 large transport wheels",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,300 × 680 × 1,050 mm",
      noiseLevel: "< 93 dB(A)",
      weight: "95 kg",
    },
  },
  8: {
    id: 8,
    name: "Vector 4S STD 13 HP Honda GX390",
    sku: "MA 034 001 209",
    engine: "13.0 HP Honda GX390",
    image: imgProductCard,
    specs: {
      engine: "13.0 HP Honda GX390",
      power: "9.7 kW / 13.0 HP",
      timberDiameter: "Ø 70 mm",
      capacity: "120 litres",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber",
      feedOpening: "100 × 60 mm",
      feedHeight: "Standard",
      collectionCapacity: "120 litres",
      durability: "Heavy-duty steel construction",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage",
      storageDimensions: "1,400 × 720 × 1,100 mm",
      wheels: "2 large transport wheels",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,400 × 720 × 1,100 mm",
      noiseLevel: "< 94 dB(A)",
      weight: "110 kg",
    },
  },
  9: {
    id: 9,
    name: "Vector 4S PRO 13 HP Honda GX390",
    sku: "MA 034 010 209",
    engine: "13.0 HP Honda GX390",
    image: imgProductCard,
    specs: {
      engine: "13.0 HP Honda GX390",
      power: "9.7 kW / 13.0 HP",
      timberDiameter: "Ø 75 mm",
      capacity: "140 litres",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber + extra insulation",
      feedOpening: "100 × 60 mm",
      feedHeight: "Standard",
      collectionCapacity: "140 litres",
      durability: "Heavy-duty steel, reinforced frame",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,400 × 720 × 1,100 mm",
      wheels: "2 large transport wheels + tow hitch",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,400 × 720 × 1,100 mm",
      noiseLevel: "< 93 dB(A)",
      weight: "120 kg",
    },
  },
  10: {
    id: 10,
    name: "Vector 4S ZR 13 HP Honda GX390",
    sku: "MA 034 020 209",
    engine: "13.0 HP Honda GX390",
    image: imgProductCard,
    specs: {
      engine: "13.0 HP Honda GX390",
      power: "9.7 kW / 13.0 HP",
      timberDiameter: "Ø 75 mm",
      capacity: "140 litres",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber + extra insulation",
      feedOpening: "100 × 60 mm",
      feedHeight: "Standard",
      collectionCapacity: "140 litres",
      durability: "Heavy-duty steel, reinforced frame",
      chassis: "Reinforced steel frame",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,400 × 720 × 1,100 mm",
      wheels: "2 large transport wheels + tow hitch",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,400 × 720 × 1,100 mm",
      noiseLevel: "< 93 dB(A)",
      weight: "125 kg",
    },
  },
  11: {
    id: 11,
    name: "Vector 4S CC 13 HP Honda GX390",
    sku: "MA 034 030 209",
    engine: "13.0 HP Honda GX390",
    image: imgProductCard,
    specs: {
      engine: "13.0 HP Honda GX390",
      power: "9.7 kW / 13.0 HP",
      timberDiameter: "Ø 75 mm",
      capacity: "140 litres",
      choppingSpeed: "2,400 rpm",
      shreddingTech: "4-way shredding system",
      blades: "4 reversible blades",
      noiseReduction: "Sound-dampened chamber + extra insulation",
      feedOpening: "100 × 60 mm",
      feedHeight: "Standard",
      collectionCapacity: "140 litres",
      durability: "Heavy-duty steel, reinforced frame",
      chassis: "Reinforced steel frame, cross-country suspension",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,400 × 720 × 1,100 mm",
      wheels: "Cross-country wheels + tow hitch",
      rotor: "4-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,400 × 720 × 1,100 mm",
      noiseLevel: "< 93 dB(A)",
      weight: "130 kg",
    },
  },
  12: {
    id: 12,
    name: "Prof 6 OW 14 HP Vanguard 400",
    sku: "MA 032 010 131",
    engine: "14 HP Vanguard 400",
    image: imgProductCard,
    specs: {
      engine: "14 HP Vanguard 400",
      power: "10.4 kW / 14 HP",
      timberDiameter: "Ø 90 mm",
      capacity: "200 litres",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "120 × 70 mm",
      feedHeight: "Standard",
      collectionCapacity: "200 litres",
      durability: "Heavy-duty steel, industrial-grade",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,600 × 800 × 1,200 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,600 × 800 × 1,200 mm",
      noiseLevel: "< 95 dB(A)",
      weight: "180 kg",
    },
  },
  13: {
    id: 13,
    name: "Prof 6 CC 14 HP Vanguard 400",
    sku: "MA 032 020 131",
    engine: "14 HP Vanguard 400",
    image: imgProductCard,
    specs: {
      engine: "14 HP Vanguard 400",
      power: "10.4 kW / 14 HP",
      timberDiameter: "Ø 90 mm",
      capacity: "200 litres",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "120 × 70 mm",
      feedHeight: "Standard",
      collectionCapacity: "200 litres",
      durability: "Heavy-duty steel, industrial-grade",
      chassis: "Reinforced steel frame, cross-country",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,600 × 800 × 1,200 mm",
      wheels: "Cross-country pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,600 × 800 × 1,200 mm",
      noiseLevel: "< 95 dB(A)",
      weight: "195 kg",
    },
  },
  14: {
    id: 14,
    name: "Prof 6 OR 14 HP Vanguard 400",
    sku: "MA 032 030 131",
    engine: "14 HP Vanguard 400",
    image: imgProductCard,
    specs: {
      engine: "14 HP Vanguard 400",
      power: "10.4 kW / 14 HP",
      timberDiameter: "Ø 90 mm",
      capacity: "200 litres",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "120 × 70 mm",
      feedHeight: "Standard",
      collectionCapacity: "200 litres",
      durability: "Heavy-duty steel, industrial-grade",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,600 × 800 × 1,200 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,600 × 800 × 1,200 mm",
      noiseLevel: "< 95 dB(A)",
      weight: "190 kg",
    },
  },
  15: {
    id: 15,
    name: "Prof 6 PTO",
    sku: "MA 032 040 000",
    engine: "PTO - ABM",
    image: imgProductCard,
    specs: {
      engine: "PTO (tractor-mounted)",
      power: "20–40 kW / 27–54 HP (via PTO)",
      timberDiameter: "Ø 100 mm",
      capacity: "N/A (ground discharge)",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber",
      feedOpening: "130 × 80 mm",
      feedHeight: "Elevated",
      collectionCapacity: "N/A (ground discharge)",
      durability: "Industrial-grade steel, tractor-grade",
      chassis: "3-point linkage mounted",
      safety: "PTO safety guard, emergency stop",
      storageDimensions: "1,700 × 850 × 1,300 mm",
      wheels: "N/A (tractor mounted)",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "PTO shaft drive",
      dimensions: "1,700 × 850 × 1,300 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "220 kg",
    },
  },
  16: {
    id: 16,
    name: "Prof 6 E-Power OW",
    sku: "MA 032 010 821",
    engine: "7.5 kW - 48 V Vanguard 7.0 kW",
    image: imgProductCard,
    specs: {
      engine: "48V electric (7.5 kW)",
      power: "7.5 kW / 10 HP",
      timberDiameter: "Ø 90 mm",
      capacity: "200 litres",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, electric motor (very quiet)",
      feedOpening: "120 × 70 mm",
      feedHeight: "Standard",
      collectionCapacity: "200 litres",
      durability: "Heavy-duty steel, industrial-grade",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,600 × 800 × 1,200 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Direct drive (electric)",
      dimensions: "1,600 × 800 × 1,200 mm",
      noiseLevel: "< 85 dB(A)",
      weight: "200 kg",
    },
  },
  17: {
    id: 17,
    name: "Prof 6 E-Power CC",
    sku: "MA 032 020 821",
    engine: "7.5 kW - 48 V Vanguard 7.0 kW",
    image: imgProductCard,
    specs: {
      engine: "48V electric (7.5 kW)",
      power: "7.5 kW / 10 HP",
      timberDiameter: "Ø 90 mm",
      capacity: "200 litres",
      choppingSpeed: "2,200 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, electric motor (very quiet)",
      feedOpening: "120 × 70 mm",
      feedHeight: "Standard",
      collectionCapacity: "200 litres",
      durability: "Heavy-duty steel, industrial-grade",
      chassis: "Reinforced steel frame, cross-country",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,600 × 800 × 1,200 mm",
      wheels: "Cross-country pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Direct drive (electric)",
      dimensions: "1,600 × 800 × 1,200 mm",
      noiseLevel: "< 85 dB(A)",
      weight: "215 kg",
    },
  },
  18: {
    id: 18,
    name: "Prof 6 Monster",
    sku: "MA 032 010 113",
    engine: "18 HP Vanguard V-Twin",
    image: imgProductCard,
    specs: {
      engine: "18 HP Vanguard V-Twin",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 100 mm",
      capacity: "250 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "140 × 80 mm",
      feedHeight: "Standard",
      collectionCapacity: "250 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,800 × 900 × 1,300 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,800 × 900 × 1,300 mm",
      noiseLevel: "< 96 dB(A)",
      weight: "250 kg",
    },
  },
  19: {
    id: 19,
    name: "Prof 6 Monster CC 18 HP Vanguard V-Twin",
    sku: "MA 032 020 113",
    engine: "18 HP Vanguard V-Twin",
    image: imgProductCard,
    specs: {
      engine: "18 HP Vanguard V-Twin",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 100 mm",
      capacity: "250 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "140 × 80 mm",
      feedHeight: "Standard",
      collectionCapacity: "250 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, cross-country",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,800 × 900 × 1,300 mm",
      wheels: "Cross-country pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,800 × 900 × 1,300 mm",
      noiseLevel: "< 96 dB(A)",
      weight: "270 kg",
    },
  },
  20: {
    id: 20,
    name: "Prof 6 Monster OR 18 HP Vanguard V-Twin",
    sku: "MA 032 030 113",
    engine: "18 HP Vanguard V-Twin",
    image: imgProductCard,
    specs: {
      engine: "18 HP Vanguard V-Twin",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 100 mm",
      capacity: "250 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "140 × 80 mm",
      feedHeight: "Standard",
      collectionCapacity: "250 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards",
      storageDimensions: "1,800 × 900 × 1,300 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "1,800 × 900 × 1,300 mm",
      noiseLevel: "< 96 dB(A)",
      weight: "260 kg",
    },
  },
  21: {
    id: 21,
    name: "Super Prof OW 18 HP Vanguard",
    sku: "MA 029 040 113",
    engine: "(18 HP) B&S Vanguard",
    image: imgProductCard,
    specs: {
      engine: "18 HP B&S Vanguard",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 120 mm",
      capacity: "300 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system + ABM",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "150 × 90 mm",
      feedHeight: "Standard",
      collectionCapacity: "300 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,000 × 1,000 × 1,400 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,000 × 1,000 × 1,400 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "320 kg",
    },
  },
  22: {
    id: 22,
    name: "Super Prof CC 18 HP Vanguard",
    sku: "MA 029 050 113",
    engine: "(18 HP) B&S Vanguard",
    image: imgProductCard,
    specs: {
      engine: "18 HP B&S Vanguard",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 120 mm",
      capacity: "300 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system + ABM",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "150 × 90 mm",
      feedHeight: "Standard",
      collectionCapacity: "300 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, cross-country",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,000 × 1,000 × 1,400 mm",
      wheels: "Cross-country pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,000 × 1,000 × 1,400 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "340 kg",
    },
  },
  23: {
    id: 23,
    name: "Super Prof OR 18 HP Vanguard",
    sku: "MA 029 070 113",
    engine: "(18 HP) B&S Vanguard",
    image: imgProductCard,
    specs: {
      engine: "18 HP B&S Vanguard",
      power: "13.4 kW / 18 HP",
      timberDiameter: "Ø 120 mm",
      capacity: "300 litres",
      choppingSpeed: "2,000 rpm",
      shreddingTech: "6-way shredding system + ABM",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "150 × 90 mm",
      feedHeight: "Standard",
      collectionCapacity: "300 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,000 × 1,000 × 1,400 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,000 × 1,000 × 1,400 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "330 kg",
    },
  },
  24: {
    id: 24,
    name: "Super Prof Max OW 23 HP EFI Vanguard",
    sku: "MA 029 040 125",
    engine: "(23 HP) B&S EFI Vanguard",
    image: imgProductCard,
    specs: {
      engine: "23 HP B&S EFI Vanguard",
      power: "17.2 kW / 23 HP",
      timberDiameter: "Ø 130 mm",
      capacity: "350 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation, EFI",
      feedOpening: "160 × 100 mm",
      feedHeight: "Standard",
      collectionCapacity: "350 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,100 × 1,100 × 1,500 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,100 × 1,100 × 1,500 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "380 kg",
    },
  },
  25: {
    id: 25,
    name: "Super Prof Max CC 23 HP EFI Vanguard",
    sku: "MA 029 050 125",
    engine: "(23 HP) B&S EFI Vanguard",
    image: imgProductCard,
    specs: {
      engine: "23 HP B&S EFI Vanguard",
      power: "17.2 kW / 23 HP",
      timberDiameter: "Ø 130 mm",
      capacity: "350 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation, EFI",
      feedOpening: "160 × 100 mm",
      feedHeight: "Standard",
      collectionCapacity: "350 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, cross-country",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,100 × 1,100 × 1,500 mm",
      wheels: "Cross-country pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,100 × 1,100 × 1,500 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "400 kg",
    },
  },
  26: {
    id: 26,
    name: "Super Prof Max OR 23 HP EFI Vanguard",
    sku: "MA 029 070 125",
    engine: "(23 HP) B&S EFIVanguard",
    image: imgProductCard,
    specs: {
      engine: "23 HP B&S EFI Vanguard",
      power: "17.2 kW / 23 HP",
      timberDiameter: "Ø 130 mm",
      capacity: "350 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation, EFI",
      feedOpening: "160 × 100 mm",
      feedHeight: "Standard",
      collectionCapacity: "350 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,100 × 1,100 × 1,500 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,100 × 1,100 × 1,500 mm",
      noiseLevel: "< 97 dB(A)",
      weight: "390 kg",
    },
  },
  27: {
    id: 27,
    name: "MEGA PROF OR 25 HP Kubota Diesel",
    sku: "MA 018 011 340",
    engine: "(25 HP) Kubota Diesel",
    image: imgProductCard,
    specs: {
      engine: "25 HP Kubota Diesel",
      power: "18.6 kW / 25 HP",
      timberDiameter: "Ø 150 mm",
      capacity: "500 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "180 × 110 mm",
      feedHeight: "Standard",
      collectionCapacity: "500 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,400 × 1,200 × 1,600 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,400 × 1,200 × 1,600 mm",
      noiseLevel: "< 98 dB(A)",
      weight: "520 kg",
    },
  },
  28: {
    id: 28,
    name: "MEGA PROF OR 40 HP Vanguard",
    sku: "MA 018 011 137",
    engine: "(37 HP) B&S EFI Vanguard",
    image: imgProductCard,
    specs: {
      engine: "37 HP B&S EFI Vanguard",
      power: "27.6 kW / 37 HP",
      timberDiameter: "Ø 160 mm",
      capacity: "500 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "180 × 110 mm",
      feedHeight: "Standard",
      collectionCapacity: "500 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on road",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,400 × 1,200 × 1,600 mm",
      wheels: "Road-approved pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,400 × 1,200 × 1,600 mm",
      noiseLevel: "< 99 dB(A)",
      weight: "540 kg",
    },
  },
  29: {
    id: 29,
    name: "MEGA PROF OW 25 HP Kubota Diesel",
    sku: "MA 018 021 340",
    engine: "(25 HP) Kubota Diesel",
    image: imgProductCard,
    specs: {
      engine: "25 HP Kubota Diesel",
      power: "18.6 kW / 25 HP",
      timberDiameter: "Ø 150 mm",
      capacity: "500 litres",
      choppingSpeed: "1,800 rpm",
      shreddingTech: "6-way shredding system + ABM + ZR",
      blades: "6 reversible blades",
      noiseReduction: "Double-wall chamber, acoustic insulation",
      feedOpening: "180 × 110 mm",
      feedHeight: "Standard",
      collectionCapacity: "500 litres",
      durability: "Industrial-grade steel, heavy-duty",
      chassis: "Reinforced steel frame, on wheels",
      safety: "Emergency stop, anti-blockage, safety guards, ABM",
      storageDimensions: "2,400 × 1,200 × 1,600 mm",
      wheels: "2 large pneumatic wheels + tow hitch",
      rotor: "6-way reversible rotor",
      cuttingWidth: "N/A",
      transmission: "Belt drive",
      dimensions: "2,400 × 1,200 × 1,600 mm",
      noiseLevel: "< 98 dB(A)",
      weight: "500 kg",
    },
  },
};

/** Get comparison data for a set of product ids */
export function getComparisonData(ids: number[]): ComparisonProductData[] {
  return ids
    .map((id) => COMPARISON_PRODUCT_DATA[id])
    .filter(Boolean);
}

/**
 * YITH “related products below the comparison table” — same WooCommerce category
 * as the first selected product. Hidden when the selection spans mixed categories.
 */
export function getRelatedInCategory(
  selectedIds: number[],
  limit = 8
): { id: number; name: string; sku: string; engine: string; image: string; category: string }[] {
  if (selectedIds.length === 0) return [];

  const selectedItems = selectedIds
    .map((id) => CATALOG.find((p) => p.id === id))
    .filter((p): p is (typeof CATALOG)[number] => Boolean(p));
  if (selectedItems.length === 0) return [];

  const category = selectedItems[0].category;
  if (!selectedItems.every((p) => p.category === category)) return [];

  return CATALOG.filter((p) => p.category === category && !selectedIds.includes(p.id))
    .slice(0, limit)
    .map((p) => ({
      id: p.id,
      name: p.name,
      sku: p.sku,
      engine: p.engine,
      category: p.category,
      image: COMPARISON_PRODUCT_DATA[p.id]?.image ?? imgProductCard,
    }));
}